name: CI
on: [ push ]
jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Intall dependencies
      run: npm ci
    - run: npm run make --if-present
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: Artifact
    #     path: out\make\squirrel.windows\x64
    #     if-no-files-found: error
